#!/usr/bin/env python

import sys
import urllib

pokedex = ['bulbasaur',
           'ivysaur',
           'venusaur',
           'charmander',
           'charmeleon',
           'charizard',
           'squirtle',
           'wartortle',
           'blastoise',
           'cataperie',
           'metapod',
           'butterfree',
           'weedle',
           'kakuna',
           'beedrill',
           'pidgey',
           'pidgeotto',
           'pidgeot',
           'rattata',
           'raticate',
           'spearow',
           'fearow',
           'ekans',
           'arbok',
           'pikachu',
           'raichu',
           'sandshrew',
           'sandslash',
           'nidoran (f)',
           'nidorina',
           'nidoqueen',
           'nidoran (m)',
           'nidorino',
           'nidoking',
           'clefairy',
           'clefable',
           'vulpix',
           'ninetails',
           'jigglypuff',
           'wigglytuff',
           'zubat',
           'golbat',
           'oddish',
           'gloom',
           'vileplume',
           'paras',
           'parasect',
           'venonat',
           'venomoth',
           'diglett',
           'dugtrio',
           'meowth',
           'persian',
           'psyduck',
           'golduck',
           'mankey',
           'primeape',
           'growlithe',
           'arcanine',
           'poliwag',
           'poliwhirl',
           'poliwrath',
           'abra',
           'kadabra',
           'alakazam',
           'machop',
           'machoke',
           'machamp',
           'bellsprout',
           'weepinbell',
           'victreebel',
           'tentacool',
           'tentacruel',
           'geodude',
           'graveler',
           'golem',
           'ponyta',
           'rapidash',
           'slowpoke',
           'slowbro',
           'magnemite',
           'magneton',
           'farfetchd',
           'doduo',
           'dodrio',
           'seel',
           'dewgong',
           'grimer',
           'muk',
           'shellder',
           'cloyster',
           'gastly',
           'haunter',
           'gengar',
           'onix',
           'drowzee',
           'hypno',
           'krabby',
           'kingler',
           'voltorb',
           'electrode',
           'exeggcute',
           'exeggutor',
           'cubone',
           'marowak',
           'hitmonlee',
           'hitmonchan',
           'lickitung',
           'koffing',
           'weezing',
           'rhyhorn',
           'rhydon',
           'chansey',
           'tangela',
           'kangaskan',
           'horsea',
           'seadra',
           'goldeen',
           'seaking',
           'staryu',
           'starmie',
           'mr mime',
           'scyther',
           'jynx',
           'electrabuzz',
           'magmar',
           'pinsir',
           'tauros',
           'magikarp',
           'gyarados',
           'lapras',
           'ditto',
           'eevee',
           'vaporeon',
           'jolteon',
           'flareon',
           'porygon',
           'omanyte',
           'omastar',
           'kabuto',
           'kabutops',
           'aerodactyl',
           'snorlax',
           'articuno',
           'zapdos',
           'moltres',
           'dratini',
           'dragonair',
           'dragonite',
           'mewtwo',
           'mew']

user = sys.argv[1]
pokemon = ' '.join(sys.argv[5:])

if pokemon.lower() in pokedex:
    index = pokedex.index(pokemon.lower())+1
    if index <= 120:
        url = 'http://www.angelfire.com/mn/Maija/pokemon/%03d.txt' % index
        data = urllib.urlopen(url)
        for line in data.readlines():
            print "|    " + line,
    else:
        print "Sorry, I can't draw %s" % pokemon
else:
    print "What's a '%s'?" % pokemon

